spring.application.name=nova
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.datasource.url=${DB_URL}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
