spring:
  mvc:
    view:
      resolver:
        enable: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "https://port-0-server-lz1cq56f81af005d.sel4.cloudtype.app/login/oauth2/code/google"

  datasource:
    url: ${DB_URL}
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver # org.mariadb.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect # org.hibernate.dialect.MariaDBDialect
      hibernate:
        ddl-auto: update
      show-sql: true

  ## datasource:
    # url: ${DB_URL}
    # username: root
    # password: ${DB_PASSWORD}
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # jpa:
      # properties:
        # hibernate:
          # dialect: org.hibernate.dialect.MySQL8Dialect
      # hibernate:
        # ddl-auto: none
      # show-sql: true

jwt:
  secret: ${jwt.secret}
  expiration: ${jwt.expiration}
